# Generated by Django 5.1.2 on 2024-10-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_mfa_secret_user_otp_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_required',
            new_name='mfa_enabled',
        ),
    ]
