# Generated by Django 5.1.2 on 2024-10-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_otp_required_user_mfa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_verified',
            field=models.BooleanField(default=False),
        ),
    ]
