services:
  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres'"]
      interval: 3s
      timeout: 1s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    restart: always
    networks:
      - ft_transcendence_dev

  frontend:
    image: frontend:0.0.1
    build:
      context: ./frontend
      dockerfile: Dockerfile.develop
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - ft_transcendence_dev
    volumes:
      - ./frontend/src:/usr/share/nginx/html/src
      - ./frontend/index.html:/usr/share/nginx/html/index.html
      - ./frontend/login.html:/usr/share/nginx/html/login.html

  backend:
    image: backend:0.0.1
    build:
      context: ./backend
      dockerfile: Dockerfile.develop
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - ft_transcendence_dev
    volumes:
      - "./backend:/app"

  load_balancer:
    image: load_balancer:0.0.1
    build:
      context: .
      dockerfile: Dockerfile.develop
    container_name: load_balancer
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - ft_transcendence_dev

volumes:
  db_data_dev:

networks:
  ft_transcendence_dev:
