FROM python:3.13.0-bookworm

WORKDIR /app

COPY ./requirements.txt .
RUN pip install -r requirements.txt

# COPY . .
# RUN chmod +x /app/docker-entrypoint.sh

EXPOSE 8000

# CMD ls ./; ./docker-entrypoint.sh
CMD [ "./docker-entrypoint.develop.sh" ]
# CMD [ "tail", "-f", "/dev/null" ]
