# Generated by Django 5.1.2 on 2024-12-08 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingame', '0002_alter_oneversusonegame_game_id'),
        ('pingpong_history', '0002_alter_pingponghistory_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneversusonegame',
            name='game_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pingpong_history.pingponghistory'),
        ),
    ]
