# Generated by Django 5.1.2 on 2024-12-14 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentMatchParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participant_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participant_user2', to=settings.AUTH_USER_MODEL)),
                ('user3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participant_user3', to=settings.AUTH_USER_MODEL)),
                ('user4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participant_user4', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tournament', 'user1', 'user2', 'user3', 'user4')},
            },
        ),
    ]
