# Generated by Django 5.1.2 on 2024-12-15 08:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournamentmatchparticipants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentmatchparticipants',
            old_name='tournament',
            new_name='tournament_id',
        ),
        migrations.AlterUniqueTogether(
            name='tournamentmatchparticipants',
            unique_together={('tournament_id', 'user1', 'user2', 'user3', 'user4')},
        ),
    ]
