# Generated by Django 5.1.2 on 2024-12-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_round_1_winner_tournament_round_2_winner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentgame',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='tournamentqueue',
            options={'ordering': ['created_at']},
        ),
    ]
