# Generated by Django 5.1.2 on 2024-12-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_tournamentgame_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgame',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
    ]
