# Generated by Django 5.1.2 on 2024-12-18 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournamentgame_ended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='multi_ball',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='option_selector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_selector', to=settings.AUTH_USER_MODEL),
        ),
    ]
