# Generated by Django 5.1.2 on 2024-12-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournament_multi_ball_tournament_option_selector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='multi_ball',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
