# Generated by Django 5.1.2 on 2024-12-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_alter_tournament_multi_ball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='current_round',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0),
        ),
        migrations.AlterField(
            model_name='tournamentgame',
            name='tournament_round',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)]),
        ),
    ]
