# Generated by Django 5.1.2 on 2024-12-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_tournament_current_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='current_game',
            field=models.IntegerField(default=1),
        ),
    ]
