# Generated by Django 5.1.2 on 2024-12-20 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_tournament_current_game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentgame',
            name='user_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_game_player_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournamentgame',
            name='user_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_game_player_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
