const data = {
    English: {
        translation: {
            auth_page_title:
                "Access the Authenticator App where 2FA is registered and enter the code number.",
            nav_home: "Home",
            nav_profile: "Profile",
            nav_settings: "Settings",
            nav_logout: "Log out",
            logout_success: "Logout successful",
            logout_fail: "Logout failed",
            btn_friend_list: "Friend List",
            btn_close: "Close",
            btn_go_matching: "Go to Matching Page",
            key_move_left_label: "Move Left",
            key_move_left_key: "◀ A",
            key_move_right_label: "Move Right",
            key_move_right_key: "D ▶",
            key_change_color_label: "Change Color",
            key_change_color_key: "C",
            key_toggle_music_label: "Toggle Music",
            key_toggle_music_key: "M",
            key_power_shot_label: "Power Shot",
            key_power_shot_key: "SPACE",
            results_title: "Results",
            start_date: "Start Date",
            end_date: "End Date",
            player_name: "Player Name",
            winner: "Winner",
            loser: "Loser",
            nav_home: "Home",
            nav_profile: "Profile",
            nav_settings: "Settings",
            nav_logout: "Log out",
            logout_success: "Logout successful",
            logout_fail: "Logout failed",
            settings_authenticator: "authenticator",
            settings_title: "Settings",
            settings_edit_profile: "Edit Profile",
            settings_2fa: "2FA Enable/Disable",
            settings_enable_2fa: "Enable 2FA",
            settings_disable_2fa: "Disable 2FA",
            settings_enable_failed_2fa: "2FA enable failed!",
            settings_disable_failed_2fa: "2FA disable failed!",
            settings_modal_cancel_btn: "Cancel",
            settings_modal_confirm_btn: "Confirm",
            settings_modal_prev_btn: "Prev",
            settings_modal_step_one_1: "",
            "addFriend-btn": "FriendAdd",
            friend_modal_message: "Search for a user.",
            friend_search: "Search",
            friend_add: "Add",
            friend_cancel: "Cancel",
            friend_not_found: "{{username}} not found or cannot be added.",
            friend_avatar_alt: "Friend Avatar",
            friend_online: "✅ Online",
            friend_offline: "❌ Offline",
            friend_delete: "Delete",
            "save-id-btn": "Save",
            btn_edit: "Edit",
            btn_cancel: "Cancel",
            matching_page_title: "Matching Page",
            matching_waiting_pvp: "Waiting for PvP User",
            matching_waiting_tournament: "Waiting for Tournament Users",
            matching_waiting_pve: "Waiting for Start",
            websocket_connected: "WebSocket connected.",
            websocket_closed: "WebSocket closed.",
            websocket_error: "WebSocket error:",
            received_data: "Received data:",
            waiting_for_opponent: "Waiting for opponent...",
            match_canceled: "Match canceled.",
            error_message: "Error: {{message}}",
            match_waiting_tournament: "Waiting for tournament users...",
            unhandled_message_type: "Unhandled message type:",
            match_found_game_id: "Match found! Game ID: {{gameId}}",
            multi_ball: "Multi-ball",
            default: "Default",
            game_option_select: "Game Option Select",
            "process-btn": "Proceed",
        },
    },
    한국어: {
        translation: {
            auth_page_title:
                "2FA를 등록한 Authenticator App에 접속해서 코드번호를 입력하세요",
            nav_home: "홈",
            nav_profile: "프로필",
            nav_settings: "설정",
            nav_logout: "로그아웃",
            logout_success: "로그아웃 성공",
            logout_fail: "로그아웃 실패",
            btn_friend_list: "친구목록",
            btn_close: "X",
            btn_go_matching: "매칭 페이지로 가기",
            key_move_left_label: "왼쪽으로 이동",
            key_move_left_key: "◀ A",
            key_move_right_label: "오른쪽으로 이동",
            key_move_right_key: "D ▶",
            key_change_color_label: "색변경",
            key_change_color_key: "C",
            key_toggle_music_label: "브금온오프",
            key_toggle_music_key: "M",
            key_power_shot_label: "파워샷",
            key_power_shot_key: "SPACE",
            results_title: "결과",
            start_date: "시작 날짜",
            end_date: "종료 날짜",
            player_name: "플레이어 이름",
            winner: "승자",
            loser: "패자",
            nav_home: "홈",
            nav_profile: "프로필",
            nav_settings: "설정",
            nav_logout: "로그아웃",
            logout_success: "로그아웃 성공",
            logout_fail: "로그아웃 실패",
            settings_authenticator: "인증",
            settings_title: "설정",
            settings_edit_profile: "프로필 수정",
            settings_2fa: "2FA 활성화/비활성화",
            settings_enable_2fa: "2FA 활성화",
            settings_disable_2fa: "2FA 비활성화",
            settings_enable_failed_2fa: "2FA 활성화 실패",
            settings_disable_failed_2fa: "2FA 비활성화 실패",
            settings_modal_cancel_btn: "취소",
            settings_modal_confirm_btn: "확인",
            settings_modal_prev_btn: "이전",
            "addFriend-btn": "친구추가",
            friend_modal_message: "유저를 검색해보세요.",
            friend_search: "검색",
            friend_add: "추가",
            friend_cancel: "취소",
            friend_not_found:
                "{{username}}님이 존재하지 않거나 추가할 수 없는 유저입니다.",
            friend_avatar_alt: "친구 아바타",
            friend_online: "✅ 온라인",
            friend_offline: "❌ 오프라인",
            friend_delete: "삭제",
            "save-id-btn": "저장",
            btn_edit: "수정",
            btn_cancel: "취소",
            matching_page_title: "매칭 페이지",
            matching_waiting_pvp: "PvP 유저 대기 중",
            matching_waiting_tournament: "토너먼트 유저 대기 중",
            matching_waiting_pve: "시작을 기다리는 중",
            websocket_connected: "WebSocket 연결됨.",
            websocket_closed: "WebSocket 연결이 끊어졌습니다.",
            websocket_error: "WebSocket 오류:",
            received_data: "데이터 수신됨:",
            waiting_for_opponent: "상대를 기다리는 중...",
            match_canceled: "매치가 취소되었습니다.",
            error_message: "오류: {{message}}",
            match_waiting_tournament: "토너먼트 참가자 대기 중...",
            unhandled_message_type: "처리되지 않은 메시지 유형:",
            match_found_game_id: "매치가 찾았습니다! 게임 ID: {{gameId}}",
            multi_ball: "공두개",
            default: "기본",
            game_option_select: "게임옵션 선택",
            "process-btn": "진행",
        },
    },
    日本語: {
        translation: {
            auth_page_title:
                "2FAを登録したAuthenticatorアプリにアクセスして、コード番号を入力してください。",
            nav_home: "ホーム",
            nav_profile: "プロフィール",
            nav_settings: "設定",
            nav_logout: "ログアウト",
            logout_success: "ログアウト成功",
            logout_fail: "ログアウト失敗",
            btn_friend_list: "友達リスト",
            btn_close: "閉じる",
            btn_go_matching: "マッチングページへ行く",
            key_move_left_label: "左へ移動",
            key_move_left_key: "◀ A",
            key_move_right_label: "右へ移動",
            key_move_right_key: "D ▶",
            key_change_color_label: "色を変える",
            key_change_color_key: "C",
            key_toggle_music_label: "音楽のオン/オフ",
            key_toggle_music_key: "M",
            key_power_shot_label: "パワーショット",
            key_power_shot_key: "SPACE",
            results_title: "結果",
            start_date: "開始日",
            end_date: "終了日",
            player_name: "プレイヤー名",
            winner: "勝者",
            loser: "敗者",
            nav_home: "ホーム",
            nav_profile: "プロフィール",
            nav_settings: "設定",
            nav_logout: "ログアウト",
            logout_success: "ログアウト成功",
            logout_fail: "ログアウト失敗",
            settings_authenticator: "にんしょうアプリ",
            settings_title: "設定",
            settings_edit_profile: "プロフィール編集",
            settings_2fa: "2FA 有効化/無効化",
            settings_enable_2fa: "2FA 有効化",
            settings_disable_2fa: "2FA 無効化",
            settings_enable_failed_2fa: "2FAの有効化に失敗する",
            settings_disable_failed_2fa: "2FAの無効化に失敗する",
            settings_modal_cancel_btn: "キャンセル",
            settings_modal_confirm_btn: "かくにん",
            settings_modal_prev_btn: "もどる",
            "addFriend-btn": "友達友達",
            friend_modal_message: "ユーザーを検索してください。",
            friend_search: "検索",
            friend_add: "追加",
            friend_cancel: "キャンセル",
            friend_not_found:
                "{{username}}は見つかりませんでした、または追加できません。",
            friend_avatar_alt: "友達のアバター",
            friend_online: "✅ オンライン",
            friend_offline: "❌ オフライン",
            friend_delete: "削除",
            "save-id-btn": "保存",
            btn_edit: "編集",
            btn_cancel: "キャンセル",
            matching_page_title: "マッチングページ",
            matching_waiting_pvp: "PvPユーザーを待機中",
            matching_waiting_tournament: "トーナメントユーザーを待機中",
            matching_waiting_pve: "開始を待っています",
            websocket_connected: "WebSocketが接続されました。",
            websocket_closed: "WebSocketが切断されました。",
            websocket_error: "WebSocketエラー:",
            received_data: "データを受信しました:",
            waiting_for_opponent: "対戦相手を待機中...",
            match_canceled: "マッチがキャンセルされました。",
            error_message: "エラー: {{message}}",
            match_waiting_tournament: "トーナメント参加者を待機中...",
            unhandled_message_type: "未処理のメッセージタイプ:",
            match_found_game_id: "マッチが見つかりました！ゲームID: {{gameId}}",
            multi_ball: "マルチボール",
            default: "デフォルト",
            game_option_select: "ゲームオプションの選択",
            "process-btn": "進む",
        },
    },
};

export default data;
