# Generated by Django 5.1.2 on 2024-12-15 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friend',
            name='unique_friendship',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='friend',
            new_name='friend_user',
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('user', 'friend_user'), name='unique_friendship'),
        ),
    ]
