# Generated by Django 5.1.2 on 2024-11-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_2fa_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mfa_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mfa_secret',
        ),
    ]
