# Generated by Django 5.1.2 on 2024-11-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_verified'),
        ('users', '0003_user_avatar'),
    ]

    operations = [
    ]
