# Generated by Django 5.1.2 on 2024-11-25 07:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PingPongHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('user1_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('user2_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('gamemode', models.CharField(max_length=255)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pingpong_games_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pingpong_games_as_user2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pingpong_games_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(fields=('user1', 'user2', 'started_at'), name='unique_game_per_time'), models.CheckConstraint(condition=models.Q(('user1', models.F('user2')), _negated=True), name='prevent_self_play')],
            },
        ),
    ]
