# Generated by Django 5.1.2 on 2024-12-09 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong_history', '0003_alter_pingponghistory_user1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingponghistory',
            name='average_rally',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pingponghistory',
            name='longest_rally',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pingponghistory',
            name='user1_powerball',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pingponghistory',
            name='user2_powerball',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
