# Generated by Django 5.1.2 on 2024-12-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong_history', '0004_pingponghistory_average_rally_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pingponghistory',
            name='user1_powerball',
        ),
        migrations.RemoveField(
            model_name='pingponghistory',
            name='user2_powerball',
        ),
    ]
