# Generated by Django 5.1.2 on 2024-12-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong_history', '0007_pingponghistory_multi_ball_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pingponghistory',
            name='multi_ball',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
