name: Django CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create .env File
      run: |
        echo "MINSEPAR_CLIENT_ID=${{ secrets.MINSEPAR_CLIENT_ID }}" >> backend/.env
        echo "MINSEPAR_SECRET=${{ secrets.MINSEPAR_SECRET }}" >> backend/.env
    - name: Install Dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: backend
      run: |
        python manage.py migrate --settings=backend.settings_test
        python manage.py test --settings=backend.settings_test
